COMMON_FLAGS="-march=tigerlake -O2 -pipe -fno-semantic-interposition"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

MAKEOPTS="-j8 -l6"

USE="alsa dbus elogind opengl udev vulkan X xft -wayland"

ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

LC_MESSAGES=C.UTF-8
